In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Mid-Level Perceptual Features/metadata_annotations/annotations.csv')
dataset.head()

song_id   melody   articulation  rhythm_complexity  rhythm_stability  \
0        1      8.8            4.0           4.000000          6.666667   
1        2      9.0            2.8           2.333333          8.000000   
2        3      7.6            8.0           6.333333          7.666667   
3        4      7.2            3.2           5.000000          6.250000   
4        5      8.0            3.8           4.750000          6.500000   

   dissonance  atonality  mode  
0         3.4        7.4  6.00  
1         2.2        7.6  3.75  
2         3.2        6.6  4.75  
3         2.4        7.8  6.20  
4         2.6        7.2  6.20

In [4]:
dataset.columns

Index(['song_id', ' melody', ' articulation', 'rhythm_complexity',
       'rhythm_stability', 'dissonance', 'atonality', 'mode'],
      dtype='object')

In [5]:
dataset.columns = dataset.columns.str.strip()

In [6]:
mid_level_perceptual_features = ['melody', 'articulation', 'rhythm_complexity',
                                 'rhythm_stability', 'dissonance', 'atonality', 'mode']
print(dataset[mid_level_perceptual_features])

      melody  articulation  rhythm_complexity  rhythm_stability  dissonance  \
0        8.8          4.00           4.000000          6.666667         3.4   
1        9.0          2.80           2.333333          8.000000         2.2   
2        7.6          8.00           6.333333          7.666667         3.2   
3        7.2          3.20           5.000000          6.250000         2.4   
4        8.0          3.80           4.750000          6.500000         2.6   
...      ...           ...                ...               ...         ...   
4995     6.4          7.25           4.333333          7.250000         5.0   
4996     5.6          8.25           4.333333          7.500000         5.8   
4997     5.0          9.00           4.333333          8.000000         6.2   
4998     6.8          6.50           3.666667          8.500000         5.2   
4999     4.0          9.00           7.333333          3.750000         8.6   

      atonality  mode  
0          7.40  6.00  
1  

In [7]:
dataset[mid_level_perceptual_features].dtypes

melody               float64
articulation         float64
rhythm_complexity    float64
rhythm_stability     float64
dissonance           float64
atonality            float64
mode                 float64
dtype: object

In [8]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtract max for numerical stability
    return exp_x / np.sum(exp_x)

In [10]:
for index, row in dataset.iterrows():
    print(f"Row {index}: {row['song_id']} - {row[mid_level_perceptual_features].values}")
    # Using np.float64 ensures higher numerical stability in the softmax function, especially when dealing with exponentiation
    data_row = np.array(row[mid_level_perceptual_features].values, dtype=np.float64)
    threshold = int(np.round(np.std(data_row)))
    print("Standard Deviation", threshold)
    # softmax_values = softmax(data_row)
    # print(f"Row {index}: {row['song_id']} - {softmax_values}")
    
    # Find the threshold value (the Nth largest value)
    top_nth_value = np.partition(data_row, -threshold)[-threshold]  # Gets the Nth largest value

    # Create a binary mask: 1 for values ≥ top_nth_value, 0 otherwise
    binary_arr = (data_row >= top_nth_value).astype(int)

    print(binary_arr)  # Example output: [0 0 0 1 1 1]
    
    dataset.loc[index, mid_level_perceptual_features] = binary_arr
    
    print("-" * 100)
    # for col, value in row[gems_annotations].items():          
    #     print(data.at[index, col])

Row 0: 1.0 - [8.8        4.         4.         6.66666667 3.4        7.4
 6.        ]
Standard Deviation 2
[1 0 0 0 0 1 0]
----------------------------------------------------------------------------------------------------
Row 1: 2.0 - [9.         2.8        2.33333333 8.         2.2        7.6
 3.75      ]
Standard Deviation 3
[1 0 0 1 0 1 0]
----------------------------------------------------------------------------------------------------
Row 2: 3.0 - [7.6        8.         6.33333333 7.66666667 3.2        6.6
 4.75      ]
Standard Deviation 2
[0 1 0 1 0 0 0]
----------------------------------------------------------------------------------------------------
Row 3: 4.0 - [7.2  3.2  5.   6.25 2.4  7.8  6.2 ]
Standard Deviation 2
[1 0 0 0 0 1 0]
----------------------------------------------------------------------------------------------------
Row 4: 5.0 - [8.   3.8  4.75 6.5  2.6  7.2  6.2 ]
Standard Deviation 2
[1 0 0 0 0 1 0]
-----------------------------------------------------

In [11]:

dataset.to_csv("Mid-Level Perceptual Features/multi_hot_encoded_mid_level_features.csv", index=False)  # Saves without the index column
dataset.head()

song_id  melody  articulation  rhythm_complexity  rhythm_stability  \
0        1     1.0           0.0                0.0               0.0   
1        2     1.0           0.0                0.0               1.0   
2        3     0.0           1.0                0.0               1.0   
3        4     1.0           0.0                0.0               0.0   
4        5     1.0           0.0                0.0               0.0   

   dissonance  atonality  mode  
0         0.0        1.0   0.0  
1         0.0        1.0   0.0  
2         0.0        0.0   0.0  
3         0.0        1.0   0.0  
4         0.0        1.0   0.0

In [3]:
dataset = pd.read_csv('Mid-Level Perceptual Features/metadata_annotations/Jamendo_download_links.csv')
dataset.head()

jamendo_id                                   title duration artist_name  \
0       10087                           Dans ce monde      178        Shex   
1       39339                           Long Distance      363        Nîco   
2         287  Portées Disparues (Femmes sans visage)      197    Alchimie   
3       21057                             Teufelsritt      271   Minnesanc   
4      112990                             Dubliftment      437     Natty I   

             album_name                                     audio_download  \
0  Des rêves et du vent  https://mp3d.jamendo.com/download/track/10087/...   
1           Poker party  https://mp3d.jamendo.com/download/track/39339/...   
2             Adversité  https://mp3d.jamendo.com/download/track/287/mp32/   
3           Teufelsritt  https://mp3d.jamendo.com/download/track/21057/...   
4  Dubbing is a must EP  https://mp3d.jamendo.com/download/track/112990...   

  vocalinstrumental lang   gender acousticelectric     speed  \
0      instrumental  NaN      NaN              NaN    medium   
1      instrumental  NaN      NaN              NaN   verylow   
2             vocal  NaN     male              NaN  veryhigh   
3      instrumental  NaN      NaN              NaN  veryhigh   
4      instrumental  NaN  neutral         electric   verylow   

                           genres          instruments  
0                     hiphop, rnb                  NaN  
1  rock, metal, funk, alternative                piano  
2          rock, pop, alternative  voice, guitar, drum  
3                           metal                  NaN  
4      reggae, dub, world, island          drum, brass

In [26]:
genres = dataset['genres'].unique()
genres = genres[~pd.isnull(genres)]

In [37]:
cleaned_genres_array = []
for genre in genres:
    genre = genre.split(',')
    for item in genre:
        cleaned_genres_array.append(item.strip())

In [56]:
from collections import Counter
frequency = Counter(cleaned_genres_array)
print(frequency['classical'])
print(frequency['pop'])
print(frequency['electronic'])
print(frequency['rock'])

73
295
270
322


In [ ]:
print(frequency)

['hiphop', 'rnb', 'rock', 'metal', 'funk', 'alternative', 'rock', 'pop', 'alternative', 'metal', 'reggae', 'dub', 'world', 'island', 'dance', 'techno', 'electronic', 'newage', 'electronic', 'minimal', 'soundtrack', 'pop', 'soundtrack', 'classical', 'soundtrack', 'ambient', 'electronic', 'soundtrack', 'newage', 'experimental', 'electronic', 'rock', 'postrock', 'pop', 'world', 'dance', 'techno', 'newage', 'electronic', 'electronic', 'minimal', 'classical', 'minimal', 'soundtrack', 'classical', 'rock', 'pop', 'metal', 'indie', 'soundtrack', 'orchestral', 'classical', 'electronic', 'rock', 'pop', 'soundtrack', 'electronic', 'alternative', 'experimental', 'world', 'ambient', 'african', 'lounge', 'rock', 'blues', 'pop', 'popfolk', 'jazz', 'lounge', 'electronic', 'easylistening', 'hiphop', 'rap', 'triphop', 'downtempo', 'reggae', 'dub', 'experimental', 'alternative', 'jazz', 'soundtrack', 'techno', 'dance', 'electropop', 'rock', 'grunge', 'rock', 'metal', 'hardrock', 'hiphop', 'trance', 'tech